from info import db

# 用户表【在用】
class Ns_contract(db.Model):
    id: object = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user = db.Column(db.String(50))
    ns = db.Column(db.String(30))
    projectId = db.Column(db.String(100))
    taskId = db.Column(db.String(100))
    image = db.Column(db.String(200))
    callback = db.Column(db.String(100))
    root_dir = db.Column(db.String(100))
    cmd = db.Column(db.String(200))
    slot = db.Column(db.String(20))
    memory = db.Column(db.String(20))
    user_id = db.Column(db.String(30))
    group_id = db.Column(db.String(30))
    priority = db.Column(db.String(50))
    workdir = db.Column(db.String(200))
    contract = db.Column(db.String(200))
    create_time = db.Column(db.String(50))

class Cloud_deliver(db.Model):
    id: object = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50))
    namespace = db.Column(db.String(50))
    projectId = db.Column(db.String(100))
    taskId = db.Column(db.String(100))
    image = db.Column(db.String(200))
    callback = db.Column(db.String(100))
    root_dir = db.Column(db.String(100))
    cmd = db.Column(db.String(200))
    slot = db.Column(db.String(20))
    memory = db.Column(db.String(20))
    user_id = db.Column(db.String(30))
    group_id = db.Column(db.String(30))
    priority = db.Column(db.String(50))
    workdir = db.Column(db.String(200))
    contract = db.Column(db.String(30))
    create_time = db.Column(db.String(50))

class Cloud_deliver_hw(db.Model):
    id: object = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50))
    namespace = db.Column(db.String(50))
    projectId = db.Column(db.String(100))
    taskId = db.Column(db.String(100))
    image = db.Column(db.String(200))
    callback = db.Column(db.String(100))
    root_dir = db.Column(db.String(100))
    cmd = db.Column(db.String(200))
    slot = db.Column(db.String(20))
    memory = db.Column(db.String(20))
    user_id = db.Column(db.String(30))
    group_id = db.Column(db.String(30))
    priority = db.Column(db.String(50))
    workdir = db.Column(db.String(200))
    contract = db.Column(db.String(30))
    create_time = db.Column(db.String(50))

class Auth_user(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    auth_user = db.Column(db.String(50))
    auth_pass = db.Column(db.String(50))

class Auth_lock(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user = db.Column(db.String(50))
    path = db.Column(db.String(100))
    memory = db.Column(db.String(20))
    namespace = db.Column(db.String(50))
    region = db.Column(db.String(10))
    create_time = db.Column(db.String(50))

class User(db.Model):
    id: object = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username: object = db.Column(db.String(50))
    password = db.Column(db.String(50))
    role = db.Column(db.String(30))