"""empty message

Revision ID: 519884ff340a
Revises: c6941639f0e6
Create Date: 2023-04-01 20:36:33.330778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519884ff340a'
down_revision = 'c6941639f0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
