"""empty message

Revision ID: 8ca52a058d0b
Revises: 519884ff340a
Create Date: 2023-04-02 10:17:58.946250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca52a058d0b'
down_revision = '519884ff340a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('auth_pass', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'auth_pass')
    # ### end Alembic commands ###
