"""empty message

Revision ID: 951a6be29194
Revises: bafc51b0b537
Create Date: 2023-04-04 12:51:58.231348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951a6be29194'
down_revision = 'bafc51b0b537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_deliver', sa.Column('workdir', sa.String(length=200), nullable=True))
    op.add_column('cloud_deliver_hw', sa.Column('workdir', sa.String(length=200), nullable=True))
    op.add_column('ns_contract', sa.Column('workdir', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ns_contract', 'workdir')
    op.drop_column('cloud_deliver_hw', 'workdir')
    op.drop_column('cloud_deliver', 'workdir')
    # ### end Alembic commands ###
