"""empty message

Revision ID: 97e0b5a24dd4
Revises: af7cd79dfc33
Create Date: 2023-04-03 17:13:33.504581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e0b5a24dd4'
down_revision = 'af7cd79dfc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_deliver', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('cloud_deliver', sa.Column('namespace', sa.String(length=50), nullable=True))
    op.add_column('cloud_deliver', sa.Column('projectId', sa.String(length=100), nullable=True))
    op.add_column('cloud_deliver', sa.Column('taskId', sa.String(length=100), nullable=True))
    op.add_column('cloud_deliver', sa.Column('image', sa.String(length=200), nullable=True))
    op.add_column('cloud_deliver', sa.Column('callback', sa.String(length=100), nullable=True))
    op.add_column('cloud_deliver', sa.Column('root_dir', sa.String(length=100), nullable=True))
    op.add_column('cloud_deliver', sa.Column('cmd', sa.String(length=200), nullable=True))
    op.add_column('cloud_deliver', sa.Column('slot', sa.String(length=20), nullable=True))
    op.add_column('cloud_deliver', sa.Column('memory', sa.String(length=20), nullable=True))
    op.add_column('cloud_deliver', sa.Column('user_id', sa.String(length=30), nullable=True))
    op.add_column('cloud_deliver', sa.Column('group_id', sa.String(length=30), nullable=True))
    op.add_column('cloud_deliver', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('cloud_deliver', sa.Column('contract', sa.String(length=30), nullable=True))
    op.add_column('ns_contract', sa.Column('projectId', sa.String(length=100), nullable=True))
    op.add_column('ns_contract', sa.Column('taskId', sa.String(length=100), nullable=True))
    op.add_column('ns_contract', sa.Column('image', sa.String(length=200), nullable=True))
    op.add_column('ns_contract', sa.Column('callback', sa.String(length=100), nullable=True))
    op.add_column('ns_contract', sa.Column('root_dir', sa.String(length=100), nullable=True))
    op.add_column('ns_contract', sa.Column('cmd', sa.String(length=200), nullable=True))
    op.add_column('ns_contract', sa.Column('slot', sa.String(length=20), nullable=True))
    op.add_column('ns_contract', sa.Column('memory', sa.String(length=20), nullable=True))
    op.add_column('ns_contract', sa.Column('user_id', sa.String(length=30), nullable=True))
    op.add_column('ns_contract', sa.Column('group_id', sa.String(length=30), nullable=True))
    op.add_column('ns_contract', sa.Column('priority', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ns_contract', 'priority')
    op.drop_column('ns_contract', 'group_id')
    op.drop_column('ns_contract', 'user_id')
    op.drop_column('ns_contract', 'memory')
    op.drop_column('ns_contract', 'slot')
    op.drop_column('ns_contract', 'cmd')
    op.drop_column('ns_contract', 'root_dir')
    op.drop_column('ns_contract', 'callback')
    op.drop_column('ns_contract', 'image')
    op.drop_column('ns_contract', 'taskId')
    op.drop_column('ns_contract', 'projectId')
    op.drop_column('cloud_deliver', 'contract')
    op.drop_column('cloud_deliver', 'priority')
    op.drop_column('cloud_deliver', 'group_id')
    op.drop_column('cloud_deliver', 'user_id')
    op.drop_column('cloud_deliver', 'memory')
    op.drop_column('cloud_deliver', 'slot')
    op.drop_column('cloud_deliver', 'cmd')
    op.drop_column('cloud_deliver', 'root_dir')
    op.drop_column('cloud_deliver', 'callback')
    op.drop_column('cloud_deliver', 'image')
    op.drop_column('cloud_deliver', 'taskId')
    op.drop_column('cloud_deliver', 'projectId')
    op.drop_column('cloud_deliver', 'namespace')
    op.drop_column('cloud_deliver', 'name')
    # ### end Alembic commands ###
