"""empty message

Revision ID: af7cd79dfc33
Revises: c19ced2a05e7
Create Date: 2023-04-02 18:53:40.907194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7cd79dfc33'
down_revision = 'c19ced2a05e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_deliver', sa.Column('create_time', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_deliver', 'create_time')
    # ### end Alembic commands ###
