"""empty message

Revision ID: bafc51b0b537
Revises: 20fac0465905
Create Date: 2023-04-03 18:14:16.689179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafc51b0b537'
down_revision = '20fac0465905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_deliver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('namespace', sa.String(length=50), nullable=True),
    sa.Column('projectId', sa.String(length=100), nullable=True),
    sa.Column('taskId', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('callback', sa.String(length=100), nullable=True),
    sa.Column('root_dir', sa.String(length=100), nullable=True),
    sa.Column('cmd', sa.String(length=200), nullable=True),
    sa.Column('slot', sa.String(length=20), nullable=True),
    sa.Column('memory', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=30), nullable=True),
    sa.Column('group_id', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('contract', sa.String(length=30), nullable=True),
    sa.Column('create_time', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_deliver_hw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('namespace', sa.String(length=50), nullable=True),
    sa.Column('projectId', sa.String(length=100), nullable=True),
    sa.Column('taskId', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('callback', sa.String(length=100), nullable=True),
    sa.Column('root_dir', sa.String(length=100), nullable=True),
    sa.Column('cmd', sa.String(length=200), nullable=True),
    sa.Column('slot', sa.String(length=20), nullable=True),
    sa.Column('memory', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=30), nullable=True),
    sa.Column('group_id', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('contract', sa.String(length=30), nullable=True),
    sa.Column('create_time', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_deliver_hw')
    op.drop_table('cloud_deliver')
    # ### end Alembic commands ###
