"""empty message

Revision ID: c19ced2a05e7
Revises: 8ca52a058d0b
Create Date: 2023-04-02 11:52:20.907723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19ced2a05e7'
down_revision = '8ca52a058d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_deliver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auth_lock', sa.Column('memory', sa.String(length=20), nullable=True))
    op.add_column('auth_lock', sa.Column('create_time', sa.String(length=50), nullable=True))
    op.add_column('ns_contract', sa.Column('create_time', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ns_contract', 'create_time')
    op.drop_column('auth_lock', 'create_time')
    op.drop_column('auth_lock', 'memory')
    op.drop_table('cloud_deliver')
    # ### end Alembic commands ###
