"""empty message

Revision ID: c547380d7608
Revises: 2794dfa28794
Create Date: 2023-04-18 17:02:59.107732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c547380d7608'
down_revision = '2794dfa28794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_lock', sa.Column('region', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_lock', 'region')
    # ### end Alembic commands ###
