"""empty message

Revision ID: fd75cad2511c
Revises: 
Create Date: 2023-04-01 12:57:29.958934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd75cad2511c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_user', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ns_contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('contract', sa.String(length=200), nullable=True),
    sa.Column('ns', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ns_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ns_user', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ns_user')
    op.drop_table('ns_contract')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
